### ISSUE TITLE
Error in command "accessible-pipeline run https://example.com"

### ISSUE THREAD

**Issue by bunnykim** [fpapado/accessible-pipeline#19]
running "accessible-pipeline run https://example.com" results in output 

```
Error: spawn ./dist/cli.js ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ./dist/cli.js',
  path: './dist/cli.js',
  spawnargs: [ 'run', 'https://example.com', '--ci', '--streaming' ]
}
```

**Comment by fpapado** [comment]
A couple of more people have run into this. I'm not sure what's causing it.
It seems to be crashing in the reporter. However, the codepath for `accessible-pipeline view` also uses the reporter, and that one works. I'll look around a bit more, to see if there's anything missing.

**Comment by zekink** [comment]
Throws the same error for me too when installed locally (as suggested by the readme) and running with `node_modules/.bin/accessible-pipeline run https://example.com`

**Comment by fpapado** [comment]
Ah, I should mention one workaround!

Using `--ci` will disable the streaming reporter, and show only the log.
The reports can then be viewed with the `accessible-pipeline view` command

```shell
accessible-pipeline run https://example.com --ci
accessible-pipeline view --file report-1234.json
```

My plan is to get rid of the sub-processing eventually, now that the core has streaming as well. I think that would get rid of the cryptic error.
